-- 코드를 입력하세요
SELECT      P.PRODUCT_ID, P.PRODUCT_NAME,
            P.PRICE * SUM(O.AMOUNT) "TOTAL_SALES"
FROM        FOOD_PRODUCT P, FOOD_ORDER O
WHERE       P.PRODUCT_ID = O.PRODUCT_ID
AND         YEAR(O.PRODUCE_DATE) = 2022
AND         MONTH(O.PRODUCE_DATE) = 5
GROUP BY    P.PRODUCT_ID
ORDER BY    TOTAL_SALES DESC, P.PRODUCT_ID ASC;